# Site settings
title: HAPPY THOUGHTS
name: HAPPY THOUGHTS
email: happythoughtsmusicnl@gmail.com
description: >
  Happy Thoughts is a Hardrock/metal band from the Netherlands
baseurl: ""
url: "https://disjfa.github.io"
github_url:  https://github.com/disjfa/happy-thoughts
github_username:  disjfa
bandcamp_url:  https://happythoughtsmusic.bandcamp.com
facebook_url:  https://www.facebook.com/happythoughtsmusic/

# Google
google_analytics:

# Build settings
markdown: kramdown

# deployment
source: site
host: 0.0.0.0
port: 5000
